receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
        
processors:
  batch:
  filter:
    error_mode: ignore
    traces:
      span:
        - 'attributes["url.path"] == "/swagger/index.html"'
        - 'attributes["url.path"] == "/swagger/v1/swagger.json"'
        - 'attributes["url.path"] == "/swagger/favicon-32x32.png"'
        - 'attributes["url.path"] == "/swagger/swagger-ui-standalone-preset.js"'
        - 'attributes["url.path"] == "/swagger/swagger-ui-bundle.js"'
        - 'attributes["url.path"] == "/swagger/swagger-ui.css"'
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: event.domain
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, service.namespace

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, filter]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [attributes, resource]
      exporters: [loki]