// <auto-generated />
using System;
using Conways.GameOfLife.Infrastructure.PostgresSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Conways.GameOfLife.Infrastructure.PostgresSQL.Migrations
{
    [DbContext(typeof(BoardDbContext))]
    partial class BoardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Conways.GameOfLife.Domain.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("Conways.GameOfLife.Domain.Generation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<bool>("Stable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool[,]>("_value")
                        .IsRequired()
                        .HasColumnType("BOOLEAN[][]")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Generations", (string)null);
                });

            modelBuilder.Entity("Conways.GameOfLife.Domain.Generation", b =>
                {
                    b.HasOne("Conways.GameOfLife.Domain.Board", null)
                        .WithMany("_generations")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("Conways.GameOfLife.Domain.Board", b =>
                {
                    b.Navigation("_generations");
                });
#pragma warning restore 612, 618
        }
    }
}
