name: Conway's Game of Life Tests

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
    
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: .NET Restore
        shell: bash
        run: dotnet restore
      
      - name: .NET Build
        shell: bash
        run: dotnet build --no-restore
        
      - name: .NET Test
        shell: bash
        run: dotnet test --no-restore --no-build